### ISSUE TITLE
[vanilla-store] createSelect를 구현합니다.

### ISSUE THREAD

**Issue by yujeong-jeon** [NaverPayDev/pie#112]
### 취지
> https://jotai.org/docs/recipes/large-objects#selectatom

jotai의 selectAtom 과 동일한 기능인 다른 Store로부터의 값을 다른 형태로 변환하여 상태를 저장하는 조회성 store를 추가합니다.

[예상 인터페이스]
```ts
export const rCodeStore = createVanillaStore('')

export const regionStore = createSelector(rCodeStore, (rCode) => ({
    rCode,
    headRCode: rCode?.slice(0, 2),
}))
```

```tsx
export default function MyComponent() {
  const {rCode, headRCode} = useGetStore(regionStore)
  // const setRegion = useSetStore(regionStore) // ❌. selector는 조회성으로 취급

  return (
    <div>시・도: {headRCode} / 시・군・구: {rCode}</div>
  )
}
```

### 참조 안정성 보장해야 함
> https://jotai.org/docs/utilities/select#hold-stable-references

jotai의 selectAtom에서는  반환된 값이 premitive가 아니라 객체일 경우, 두번째 인자의 함수가 호출될 때마다 새 객체를 반환하면 React는 참조가 달라졌다고 판단하고 불필요한 리렌더링이 발생합니다. 이러한 문제가 createSelector에도 충분히 나타날 수 있는 문제로 인식하고 deepEquals 로직을 내재화하거나 사용자가 주입하도록 해야 합니다.

```ts
export const regionStore = createSelector(rCodeStore, (rCode) => ({
    rCode,
    headRCode: rCode?.slice(0, 2),
}), deepEquals)
```

**Comment by yceffort-naver** [comment]
@yujeong-jeon 님 이거 닫아도 될까요?
