### ISSUE TITLE
[vanilla-store] vanilla store 이관

### ISSUE THREAD

**Issue by keemhyunseok** [NaverPayDev/pie#84]
- 바닐라 스토어 이관
- [ ] 글쓰기
- [ ] 카나리 테스트
- [ ] 정식 배포
- [ ] 기존 vanilla store npay버전 replace

**Comment by yceffort-naver** [comment]
@keemhyunseok 님, 닫을까요?

**Comment by keemhyunseok** [comment]
아아 닫겠습니당
